version: 2.1

jobs:
  backend-build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          command: npm ci
          working_directory: backend
      - run:
          command: npm run lint
          working_directory: backend
      - run:
          command: npm run prettier:check
          working_directory: backend
      - run:
          command: npm run test:ci
          working_directory: backend
          environment:
            JWT_SECRET: jwt secret for tests
            COOKIE_SECRET: cookie secret for tests

  frontend-build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          command: npm ci
          working_directory: frontend
      - run:
          command: npm run build
          working_directory: frontend
      - run:
          command: npm run lint
          working_directory: frontend
      - run:
          command: npm run prettier:check
          working_directory: frontend
      - run:
          # using test:ci because npm test does not terminate on CircleCI
          # even though it should according to https://create-react-app.dev/docs/running-tests
          command: npm run test:ci
          working_directory: frontend
      - persist_to_workspace:
          root: ./
          paths: [frontend/build/]

  deploy:
    parameters:
      clever-app-id:
        type: string
      deploy-dir:
        type: string
        default: ../deploy
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Package
          command: |
            mkdir --parents << parameters.deploy-dir >>/public
            cp --recursive backend/* << parameters.deploy-dir >>/
            cp --recursive frontend/build/* << parameters.deploy-dir >>/public/
      - run:
          name: Deploy
          command: |
            git config --global user.email "dsi@zenika.com"
            git config --global user.name "Zenika"
            git init
            git add .
            git commit -m "deploy!"
            sudo npm install --global clever-tools
            clever login --secret=$CLEVER_SECRET --token=$CLEVER_TOKEN
            clever link << parameters.clever-app-id >>
            clever deploy --force
          working_directory: << parameters.deploy-dir >>

workflows:
  build:
    jobs:
      - backend-build
      - frontend-build
      - deploy:
          name: deploy-prod
          requires:
            - backend-build
            - frontend-build
          filters:
            branches:
              only: master
          clever-app-id: app_5131bf64-5cd8-4bcc-ae34-86b739099c73
          context: clever-cloud2-zenika-dev
