version: 2.1

jobs:
  backend-build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          command: npm ci
          working_directory: backend
      - run:
          command: npm run lint
          working_directory: backend
      - run:
          command: npm run prettier:check
          working_directory: backend
      - run:
          command: npm test
          working_directory: backend
          environment:
            JWT_SECRET: jwt secret for tests
            COOKIE_SECRET: cookie secret for tests

  frontend-build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          command: npm ci
          working_directory: frontend
      - run:
          command: npm run build
          working_directory: frontend
      - run:
          command: npm run lint
          working_directory: frontend
      - run:
          command: npm run prettier:check
          working_directory: frontend
      - run:
          # using test:ci because npm test does not terminate on CircleCI
          # even though it should according to https://create-react-app.dev/docs/running-tests
          command: npm run test:ci
          working_directory: frontend

workflows:
  build:
    jobs:
      - backend-build
      - frontend-build
